use_frameworks!

platform :ios, '8.0'

target 'CPKongTableView_Example' do
  pod 'CPKongTableView', :path => '../'

  target 'CPKongTableView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
